"""add backtest runs table

Revision ID: 2f9216bd92c0
Revises: 99d6a6e10268
Create Date: 2026-09-03 21:51:38.939580

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2f9216bd92c0"
down_revision: str | None = "99d6a6e10268"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_runs",
        sa.Column("training_job_id", sa.Uuid(), nullable=False),
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column(
            "timeframe", sa.String(length=20), nullable=False, comment="Denormalized from the job."
        ),
        sa.Column(
            "step",
            sa.String(length=20),
            nullable=False,
            comment="The walk step's own timeframe — the job's own timeframe unless a coarser one was requested.",
        ),
        sa.Column("requested_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("requested_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "truncated",
            sa.Boolean(),
            nullable=False,
            comment="True if MAX_BACKTEST_STEPS capped the requested range short.",
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "total_steps",
            sa.Integer(),
            nullable=False,
            comment="The planned number of steps, after capping.",
        ),
        sa.Column("completed_steps", sa.Integer(), nullable=False),
        sa.Column(
            "graded_count",
            sa.Integer(),
            nullable=False,
            comment="How many of this run's own predictions were successfully graded.",
        ),
        sa.Column(
            "model_kind",
            sa.String(length=24),
            nullable=False,
            comment="'classification' or 'regression', resolved the same way a live prediction's own model_kind is — from the model adapter registry, not re-derived.",
        ),
        sa.Column("aggregate_metrics", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')",
            name=op.f("ck_backtest_runs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
            name=op.f("fk_backtest_runs_experiment_id_experiments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["training_job_id"],
            ["training_jobs.id"],
            name=op.f("fk_backtest_runs_training_job_id_training_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_runs")),
    )
    op.create_index(
        op.f("ix_backtest_runs_experiment_id"), "backtest_runs", ["experiment_id"], unique=False
    )
    op.create_index(op.f("ix_backtest_runs_status"), "backtest_runs", ["status"], unique=False)
    op.create_index(op.f("ix_backtest_runs_symbol"), "backtest_runs", ["symbol"], unique=False)
    op.create_index(
        op.f("ix_backtest_runs_training_job_id"), "backtest_runs", ["training_job_id"], unique=False
    )
    op.add_column(
        "predictions",
        sa.Column(
            "backtest_run_id",
            sa.Uuid(),
            nullable=True,
            comment="Set only for a prediction the Backtesting Engine generated; NULL for every ordinary live POST /predictions/run call. See this model's own docstring.",
        ),
    )
    op.create_index(
        op.f("ix_predictions_backtest_run_id"), "predictions", ["backtest_run_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_predictions_backtest_run_id_backtest_runs"),
        "predictions",
        "backtest_runs",
        ["backtest_run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # Autogenerate also detected a one-word comment-only drift on
    # ml_dataset_builds.ml_dataset_id ("duplicated for lookup" vs "duplicated
    # here for lookup") — pre-existing, unrelated to this migration's own
    # change (see the identical note in 35fe2827d1fb, which first found it),
    # and deliberately left out again so this migration does exactly one
    # thing. Not applied here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_predictions_backtest_run_id_backtest_runs"), "predictions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_predictions_backtest_run_id"), table_name="predictions")
    op.drop_column("predictions", "backtest_run_id")
    op.drop_index(op.f("ix_backtest_runs_training_job_id"), table_name="backtest_runs")
    op.drop_index(op.f("ix_backtest_runs_symbol"), table_name="backtest_runs")
    op.drop_index(op.f("ix_backtest_runs_status"), table_name="backtest_runs")
    op.drop_index(op.f("ix_backtest_runs_experiment_id"), table_name="backtest_runs")
    op.drop_table("backtest_runs")
    # ### end Alembic commands ###
