"""create training framework schema

Revision ID: 8cc1992f6c6f
Revises: fa0a2a1c8181
Create Date: 2026-08-26 08:54:34.004251

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8cc1992f6c6f"
down_revision: str | None = "fa0a2a1c8181"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_jobs",
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column(
            "dataset_version",
            sa.String(length=200),
            nullable=True,
            comment="The dataset citation this job trains over; defaults from the experiment.",
        ),
        sa.Column(
            "model_type",
            sa.String(length=100),
            nullable=False,
            comment="A registered model adapter name (app/training/registry.py), e.g. 'placeholder'.",
        ),
        sa.Column(
            "hyperparameters",
            sa.JSON(),
            nullable=True,
            comment="Arbitrary hyperparameters passed verbatim to the model adapter.",
        ),
        sa.Column("status", sa.String(length=24), server_default="pending", nullable=False),
        sa.Column(
            "current_stage",
            sa.String(length=32),
            nullable=True,
            comment="The pipeline stage last entered; set while running, frozen on failure.",
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "result_summary",
            sa.JSON(),
            nullable=True,
            comment="Fabricated placeholder metrics/summary produced by the model adapter.",
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_training_jobs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
            name=op.f("fk_training_jobs_experiment_id_experiments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_jobs")),
    )
    op.create_index(
        op.f("ix_training_jobs_experiment_id"), "training_jobs", ["experiment_id"], unique=False
    )
    op.create_table(
        "training_job_logs",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("level", sa.String(length=16), server_default="info", nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "logged_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "level IN ('debug', 'info', 'warning', 'error')",
            name=op.f("ck_training_job_logs_level_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["training_jobs.id"],
            name=op.f("fk_training_job_logs_job_id_training_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_job_logs")),
    )
    op.create_index(
        op.f("ix_training_job_logs_job_id"), "training_job_logs", ["job_id"], unique=False
    )
    op.create_index(
        "ix_training_job_logs_job_logged_at",
        "training_job_logs",
        ["job_id", "logged_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_training_job_logs_job_logged_at", table_name="training_job_logs")
    op.drop_index(op.f("ix_training_job_logs_job_id"), table_name="training_job_logs")
    op.drop_table("training_job_logs")
    op.drop_index(op.f("ix_training_jobs_experiment_id"), table_name="training_jobs")
    op.drop_table("training_jobs")
    # ### end Alembic commands ###
