"""create market data schema

Revision ID: 592cf2283d14
Revises:
Create Date: 2026-08-11 21:23:20.025224

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "592cf2283d14"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchanges",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("slug", sa.String(length=32), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(name) > 0 AND length(slug) > 0", name=op.f("ck_exchanges_name_slug_nonempty")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchanges")),
        sa.UniqueConstraint("name", name=op.f("uq_exchanges_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_exchanges_slug")),
    )
    op.create_table(
        "markets",
        sa.Column("exchange_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("base_asset", sa.String(length=16), nullable=False),
        sa.Column("quote_asset", sa.String(length=16), nullable=False),
        sa.Column("market_type", sa.String(length=24), server_default="spot", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "market_type IN ('spot', 'perpetual', 'expiry')",
            name=op.f("ck_markets_market_type_valid"),
        ),
        sa.CheckConstraint("base_asset <> quote_asset", name=op.f("ck_markets_base_not_quote")),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["exchanges.id"],
            name=op.f("fk_markets_exchange_id_exchanges"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_markets")),
        sa.UniqueConstraint("exchange_id", "symbol", name="uq_markets_exchange_symbol"),
    )
    op.create_index(op.f("ix_markets_exchange_id"), "markets", ["exchange_id"], unique=False)
    op.create_table(
        "candles",
        sa.Column("market_id", sa.Uuid(), nullable=False),
        sa.Column("timeframe", sa.String(length=16), nullable=False),
        sa.Column("open_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("close_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("high", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("low", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("close", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("volume", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("quote_volume", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("trade_count", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "timeframe IN ('1m', '3m', '5m', '15m', '30m', '1h', '2h', '4h', '6h', '8h', '12h', '1d', '1w')",
            name=op.f("ck_candles_timeframe_valid"),
        ),
        sa.CheckConstraint("close_time > open_time", name=op.f("ck_candles_time_ordered")),
        sa.CheckConstraint("high >= open AND high >= close", name=op.f("ck_candles_high_dominant")),
        sa.CheckConstraint("low <= open AND low <= close", name=op.f("ck_candles_low_dominant")),
        sa.CheckConstraint("low >= 0", name=op.f("ck_candles_prices_nonnegative")),
        sa.CheckConstraint("trade_count >= 0", name=op.f("ck_candles_trade_count_nonnegative")),
        sa.CheckConstraint(
            "volume >= 0 AND quote_volume >= 0", name=op.f("ck_candles_volume_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
            name=op.f("fk_candles_market_id_markets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candles")),
        sa.UniqueConstraint(
            "market_id", "timeframe", "open_time", name="uq_candles_market_timeframe_open_time"
        ),
    )
    op.create_index(op.f("ix_candles_market_id"), "candles", ["market_id"], unique=False)
    op.create_index(
        "ix_candles_market_timeframe_time_desc",
        "candles",
        ["market_id", "timeframe", sa.literal_column("open_time DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_candles_market_timeframe_time_desc", table_name="candles")
    op.drop_index(op.f("ix_candles_market_id"), table_name="candles")
    op.drop_table("candles")
    op.drop_index(op.f("ix_markets_exchange_id"), table_name="markets")
    op.drop_table("markets")
    op.drop_table("exchanges")
    # ### end Alembic commands ###
