"""add training job error_detail

Revision ID: 831eb3883543
Revises: ed0d4f9becf1
Create Date: 2026-08-27 00:33:53.830036

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "831eb3883543"
down_revision: str | None = "ed0d4f9becf1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training_jobs",
        sa.Column(
            "error_detail",
            sa.JSON(),
            nullable=True,
            comment="Structured failure report (reason/affected_feature/affected_rows/suggested_fix).",
        ),
    )
    op.alter_column(
        "training_jobs",
        "symbol",
        existing_type=sa.VARCHAR(length=50),
        comment="Market symbol to load real candles from; required by a requires_real_data model.",
        existing_comment="Market symbol to load real candles from; required by a requires_real_data adapter.",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "training_jobs",
        "symbol",
        existing_type=sa.VARCHAR(length=50),
        comment="Market symbol to load real candles from; required by a requires_real_data adapter.",
        existing_comment="Market symbol to load real candles from; required by a requires_real_data model.",
        existing_nullable=True,
    )
    op.drop_column("training_jobs", "error_detail")
    # ### end Alembic commands ###
