"""add paper trading schema

Revision ID: 7a3254fe72af
Revises: 2f9216bd92c0
Create Date: 2026-09-04 09:50:42.309582

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "7a3254fe72af"
down_revision: str | None = "2f9216bd92c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_accounts",
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("starting_balance", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("balance", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("balance >= 0", name=op.f("ck_paper_accounts_balance_non_negative")),
        sa.CheckConstraint(
            "starting_balance >= 0", name=op.f("ck_paper_accounts_starting_balance_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_accounts")),
    )
    op.create_table(
        "paper_orders",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column(
            "raw_price",
            sa.Numeric(precision=38, scale=18),
            nullable=False,
            comment="The resolved quote price, before slippage.",
        ),
        sa.Column(
            "fill_price",
            sa.Numeric(precision=38, scale=18),
            nullable=False,
            comment="What the account was actually charged/credited — raw_price with slippage applied.",
        ),
        sa.Column("fill_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "price_source",
            sa.String(length=20),
            nullable=False,
            comment="'ticker' | 'trade' | 'candle_close' — which real data this fill priced from.",
        ),
        sa.Column(
            "price_observed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the quote itself was observed (event_time, or the fallback candle's own open_time).",
        ),
        sa.Column(
            "is_stale_price",
            sa.Boolean(),
            nullable=False,
            comment="True if price_observed_at was already older than the staleness threshold at fill time.",
        ),
        sa.Column(
            "slippage_applied",
            sa.Numeric(precision=38, scale=18),
            nullable=False,
            comment="abs(fill_price - raw_price) — always visible, never folded silently into fill_price.",
        ),
        sa.Column("fee_applied", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column(
            "notional",
            sa.Numeric(precision=38, scale=18),
            nullable=False,
            comment="fill_price * quantity.",
        ),
        sa.Column(
            "realized_pnl",
            sa.Numeric(precision=38, scale=18),
            nullable=True,
            comment="Set only for a sell (this order's own contribution to realized PnL); NULL for a buy.",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "price_source IN ('ticker', 'trade', 'candle_close')",
            name=op.f("ck_paper_orders_price_source_valid"),
        ),
        sa.CheckConstraint("side IN ('buy', 'sell')", name=op.f("ck_paper_orders_side_valid")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_paper_orders_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["paper_accounts.id"],
            name=op.f("fk_paper_orders_account_id_paper_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_orders")),
    )
    op.create_index(
        op.f("ix_paper_orders_account_id"), "paper_orders", ["account_id"], unique=False
    )
    op.create_index(op.f("ix_paper_orders_symbol"), "paper_orders", ["symbol"], unique=False)
    op.create_table(
        "paper_positions",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("average_entry_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_paper_positions_quantity_non_negative")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["paper_accounts.id"],
            name=op.f("fk_paper_positions_account_id_paper_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_positions")),
        sa.UniqueConstraint("account_id", "symbol", name="uq_paper_positions_account_symbol"),
    )
    op.create_index(
        op.f("ix_paper_positions_account_id"), "paper_positions", ["account_id"], unique=False
    )
    op.create_index(op.f("ix_paper_positions_symbol"), "paper_positions", ["symbol"], unique=False)
    # Autogenerate also detected a one-word comment-only drift on
    # ml_dataset_builds.ml_dataset_id ("duplicated for lookup" vs "duplicated
    # here for lookup") — pre-existing, unrelated to this migration's own
    # change (see the identical note in 35fe2827d1fb, which first found it,
    # and 2f9216bd92c0, which repeated it), and deliberately left out again
    # so this migration does exactly one thing. Not applied here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_paper_positions_symbol"), table_name="paper_positions")
    op.drop_index(op.f("ix_paper_positions_account_id"), table_name="paper_positions")
    op.drop_table("paper_positions")
    op.drop_index(op.f("ix_paper_orders_symbol"), table_name="paper_orders")
    op.drop_index(op.f("ix_paper_orders_account_id"), table_name="paper_orders")
    op.drop_table("paper_orders")
    op.drop_table("paper_accounts")
    # ### end Alembic commands ###
