"""add training job data source and target column fields

Revision ID: ed0d4f9becf1
Revises: 8cc1992f6c6f
Create Date: 2026-08-26 22:46:08.547245

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ed0d4f9becf1"
down_revision: str | None = "8cc1992f6c6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training_jobs",
        sa.Column(
            "symbol",
            sa.String(length=50),
            nullable=True,
            comment="Market symbol to load real candles from; required by a requires_real_data adapter.",
        ),
    )
    op.add_column(
        "training_jobs",
        sa.Column(
            "timeframe",
            sa.String(length=20),
            nullable=True,
            comment="Candle timeframe to load, e.g. '1h'; required by a requires_real_data adapter.",
        ),
    )
    op.add_column(
        "training_jobs",
        sa.Column(
            "target_column",
            sa.String(length=100),
            nullable=True,
            comment="Which built target column to predict; defaults to the first one built.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("training_jobs", "target_column")
    op.drop_column("training_jobs", "timeframe")
    op.drop_column("training_jobs", "symbol")
    # ### end Alembic commands ###
